# Automatically generated by: ros2nix --distro jazzy --flake --license Apache-2.0
# Copyright 2025 None
# Distributed under the terms of the Apache-2.0 license
{
  lib,
  buildRosPackage,
  ament-cmake,
  controller-interface,
  kdl-parser,
  pluginlib,
  rclcpp,
  realtime-tools,
  ros-environment,
  trajectory-msgs,
}:
buildRosPackage rec {
  pname = "ros-jazzy-cartesian-controller-base";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ament-cmake ros-environment];
  propagatedBuildInputs = [controller-interface kdl-parser pluginlib rclcpp realtime-tools trajectory-msgs];
  nativeBuildInputs = [ament-cmake];

  meta = {
    description = "The cartesian_controller_base package";
    license = with lib.licenses; [bsd3];
  };
}
