# Automatically generated by: ros2nix --distro jazzy --flake --license Apache-2.0

# Copyright 2025 None
# Distributed under the terms of the Apache-2.0 license

{ lib, buildRosPackage, cartesian-controller-base, controller-interface, rclcpp }:
buildRosPackage rec {
  pname = "ros-jazzy-cartesian-motion-controller";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  propagatedBuildInputs = [ cartesian-controller-base controller-interface rclcpp ];

  meta = {
    description = "The cartesian_motion_controller package";
    license = with lib.licenses; [ bsd3 ];
  };
}
