# Automatically generated by: ros2nix --distro jazzy --flake --license Apache-2.0

# Copyright 2025 None
# Distributed under the terms of the Apache-2.0 license

{ lib, buildRosPackage, ament-cmake, geometry-msgs, launch, launch-ros, rclcpp, sensor-msgs }:
buildRosPackage rec {
  pname = "ros-jazzy-cartesian-controller-utilities";
  version = "0.1.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ geometry-msgs launch launch-ros rclcpp sensor-msgs ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "Make the spacemouse a teach device for contact-based teleoperation";
    license = with lib.licenses; [ bsd3 ];
  };
}
