# Automatically generated by: ros2nix --distro jazzy --flake --license Apache-2.0

# Copyright 2025 None
# Distributed under the terms of the Apache-2.0 license

{ lib, buildRosPackage, ament-cmake, cartesian-controller-base, controller-interface, geometry-msgs, interactive-markers, kdl-parser, pluginlib, rclcpp, urdf }:
buildRosPackage rec {
  pname = "ros-jazzy-cartesian-controller-handles";
  version = "0.0.0";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ];
  propagatedBuildInputs = [ cartesian-controller-base controller-interface geometry-msgs interactive-markers kdl-parser pluginlib rclcpp urdf ];
  nativeBuildInputs = [ ament-cmake ];

  meta = {
    description = "The cartesian_controller_handles package";
    license = with lib.licenses; [ bsd3 ];
  };
}
